spring:
  application:
    name: api-gateway  # Service registers under this name
info:
  component: ApiGateway Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  routes:
    command-service: /command/**
    api-gateway: /api/**
  ignored-services: '*'

server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

# Discovery Client Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
management:
  security:
    enabled: false
