server:
  port: 8761
spring:
  application:
    name: discovery-service
# Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
  thymeleaf:
    enabled: false

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false

# Spring Actuator
endpoints:
  health:
    sensitive: false
management:
  security:
    enabled: false
# Hystrix (defaults: coreSize=10, timeout.enabled=true)
hystrix:
  threadpool:
    default:
      coreSize: 10
  command:
    default:
      execution:
        timeout:
          enabled: false
