spring:
  application:
    name: event-processor  # Service registers under this name
  datasource:
    url: jdbc:mysql://localhost:3306/bhn
    username: bhn
    password: password
    driverClassName: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  #cloud:
    #stream:
      #bindings:
        #input:
          #destination: timerTopic
          #content-type: application/json
          #group: timerGroup
      #kafka:
        #bindings:
          #input:
            #consumer:
              #resetOffsets: true
kafka:
  bootstrap-servers: localhost:9092
  topic:
    order-json: order.t
# Discovery Server Access
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

# Spring Actuator
endpoints:
  health:
    sensitive: false
logging:
  level:
    ROOT: INFO
server:
  port: 8083