# Spring properties
spring:
  application:
    name: order-service  # Service registers under this name
  datasource:
    url: jdbc:mysql://localhost:3306/bhn
    username: bhn
    password: password
    driverClassName: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

# Discovery Server Access
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

# Spring Actuator
endpoints:
  health:
    sensitive: false

# Hystrix (defaults: coreSize=10, timeout.enabled=true)
hystrix:
  threadpool:
    default:
      coreSize: 10
  command:
    default:
      execution:
        timeout:
          enabled: false

# HTTP Server
server:
  port: 4444   # HTTP (Tomcat) port

logging:
  level:
    ROOT: INFO
hello:
  world: hello world from remote origin app.yml
